#!/usr/bin/env bash
# Install nginx web server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP' # Nginx should be listening on port 80
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
