#!/usr/bin/env bash
# setting up nginx to listen from port 80
sudo apt-get remove -y --purge nginx nginx-common
sudo apt-get -y update
sudo apt-get install -y nginx
sudo ufw allow "Nginx HTTP"
sudo service nginx restart
