#!/usr/bin/env bash
# Configure Nginx server to redirecting to error page
sudo apt-get remove -y --purge nginx nginx-common
sudo apt-get -y update
sudo apt-get install -y nginx
sudo ufw allow "Nginx HTTP"
sudo service nginx restart
