#!/usr/bin/env bash
# fix listenign from port 80 and kill nginx process
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
echo 10000 > /var/run/nginx.pid
