#!/usr/bin/env bash
# Bash script that kills 4-to_infinity_and_beyond process. Using "Kill" this command kills the process with that name https://linux.die.net/Bash-Beginners-Guide/sect_12_01.html
kill "$(pgrep -f "4-to_infinity_and_beyond")"
