#!/usr/bin/env bash
# Bash script that kills 4-to_infinity_and_beyond process. You cannot use kill or killall. pkill -> kill processes without specifying their PID.
pkill -f "4-to_infinity_and_beyond"
