#!/usr/bin/env bash
# trap when receiving a SIGTERM signal
trap "echo 'I am invincible!!!'" SIGTERM
loop_infinitely=1
while (( loop_infinitely )); do
    echo "To infinity and beyond"
    sleep 2
done
