#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
i=0
while [ $i -le 12 ]
    echo "Hour: $i"
do
    j=1
    while [ $j -le 59 ]
    do
        echo "$j"
        let j++
    done
    let i++
done
