#!/usr/bin/env bash
# Bash script that gives you information about the holbertonschool file.
file="holbertonschool"
if test -e "$file"; then # -e ask if file exists
    echo "$file file exists"
    if [ ! -s $file ]; then # ! -s this is if doesn't have content negation
        echo "holbertonschool file is empty"
    else
        echo "holbertonschool file is not empty"
    fi
    if test -f "$file"; then  # -f ask if is regular file
        echo "holbertonschool is a regular file"
    fi
else
    echo "$file file does not exist"
fi
